/*
 * Copyright (c) 2015, Nightfall Group
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package moe.nightfall.instrumentality.editor;

import org.lwjgl.opengl.GL11;

/**
 * Created on 02/09/15.
 */
public class UIFont {
    /*
     * +-----
     * | 0   1
     * |      2
     * |
     * |      3
     * | 5   4
     * |6
     * |
     * |7
     * | 8   9
     * curves can be L(oop) S(trip) or B(asic GL_LINES)
     */
    public static String[] fontDB = {
            "0",
            "SSB",
            "  0 1  ",
            "     2 ",
            "       ",
            "      3",
            "       ",
            "9     4",
            "       ",
            " 8   5 ",
            "  7 6  ",

            "  3    ",
            " 2     ",
            "       ",
            "1      ",
            "       ",
            "0      ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "   1   ",
            "       ",
            "   0   ",
            "       ",
            "       ",
            "       ",

            "1",
            "SB",
            "  12   ",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   3   ",
            "6 7 4 5",

            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "  0    ",

            "2",
            "S",
            "  1 2  ",
            "0     3",
            "       ",
            "       ",
            "    4  ",
            "  5    ",
            "       ",
            "6      ",
            "  7   8",

            "3",
            "SS",
            "  2 3  ",
            "1     4",
            "       ",
            "      5",
            "  7 6  ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "    0  ",
            "      1",
            "       ",
            "5     2",
            "  4 3  ",

            "4",
            "SB",
            "    1  ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",
            "       ",
            "       ",
            "    2  ",

            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",

            "5",
            "S",
            "1     0",
            "       ",
            "       ",
            "  3 4  ",
            "2      ",
            "      5",
            "      6",
            "9      ",
            "  8 7  ",

            "6",
            "SS",
            "  2 1  ",
            "3     0",
            "       ",
            "       ",
            "4     9",
            "       ",
            "       ",
            "5     8",
            "  6 7  ",

            "       ",
            "       ",
            "       ",
            "  2 1  ",
            "3     0",
            "       ",
            "       ",
            "       ",
            "       ",

            "7",
            "S",
            "0    1 ",
            "      2",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "3      ",

            "8",
            "LS",
            "  1 2  ",
            "0     3",
            "       ",
            "7     4",
            "  6 5  ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "  0 7  ",
            "1     6",
            "       ",
            "2     5",
            "  3 4  ",

            "9",
            "LS",
            "  1 2  ",
            "0     3",
            "       ",
            "7     4",
            "  6 5  ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "      0",
            "       ",
            "      1",
            "       ",
            "     2 ",
            "   3   ",

// lowercase a-z

            "a",
            "LS",
            "       ",
            "       ",
            "       ",
            "       ",
            "  6 5  ",
            "7     4",
            "       ",
            "0     3",
            "  1 2  ",

            "       ",
            "       ",
            "  3 2  ",
            "4     1",
            "       ",
            "      0",
            "       ",
            "       ",
            "       ",

            "b",
            "S",
            "0      ",
            "       ",
            "       ",
            "7   6  ",
            "       ",
            "      5",
            "1     4",
            "       ",
            "  2 3  ",

            "c",
            "S",
            "       ",
            "       ",
            "  1   0",
            "       ",
            "2      ",
            "       ",
            "3      ",
            "       ",
            "  4   5",

            "d",
            "S",
            "      0",
            "       ",
            "       ",
            "  6   7",
            "       ",
            "5      ",
            "4     1",
            "       ",
            "  3 2  ",

            "e",
            "LS",
            "       ",
            "       ",
            "  0 1  ",
            "7     2",
            "6     3",
            "  5 4  ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",
            "       ",
            "1      ",
            " 2     ",
            "      3",

            "f",
            "SB",
            "      3",
            "   2   ",
            "       ",
            "  1    ",
            "       ",
            "       ",
            "       ",
            "       ",
            "  0    ",

            "       ",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "g",
            "LS",
            "       ",
            "       ",
            " 0   1 ",
            "7     2",
            "6     3",
            " 5   4 ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "      0",
            "      1",
            "       ",
            "     2 ",
            "4  3   ",

            "h",
            "BS",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "1      ",

            "       ",
            "       ",
            "       ",
            "  1 2  ",
            "0     3",
            "       ",
            "       ",
            "       ",
            "      4",

            "i",
            "B",
            "       ",
            "  0 1  ",
            "       ",
            "   2   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   3   ",

            "j",
            "BS",
            "    0 1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "     0 ",
            "       ",
            "       ",
            "     1 ",
            "       ",
            "    2  ",
            "4 3    ",

            "k",
            "BB",
            "       ",
            "       ",
            "      5",
            "       ",
            "       ",
            "4      ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "0      ",
            "       ",
            "       ",
            "2      ",
            "       ",
            "       ",
            "1     3",

            "l",
            "S",
            "       ",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "1      ",
            " 2     ",
            "   3  4",

            "m",
            "SS",
            "       ",
            "       ",
            "  2    ",
            "1  3   ",
            "       ",
            "       ",
            "       ",
            "   4   ",
            "0      ",

            "       ",
            "       ",
            "    1  ",
            "   0  2",
            "       ",
            "       ",
            "       ",
            "       ",
            "      3",

            "n",
            "S",
            "       ",
            "       ",
            "  2 3  ",
            "1     4",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     5",

            "o",
            "L",
            "       ",
            "       ",
            " 9   8 ",
            "0     7",
            "       ",
            "       ",
            "       ",
            "1     6",
            " 2   5 ",

            "p",
            "S",
            "       ",
            "       ",
            " 2   3 ",
            "1     4",
            "      5",
            "7    6 ",
            "       ",
            "       ",
            "0      ",

            "q",
            "S",
            "       ",
            "       ",
            " 3   2 ",
            "4     1",
            "5      ",
            " 6    7",
            "       ",
            "       ",
            "      0",

            "r",
            "S",

            "       ",
            "       ",
            "  2   3",
            "       ",
            "1      ",
            "       ",
            "       ",
            "       ",
            "0      ",

            "s",
            "S",
            "       ",
            "       ",
            "  2 1  ",
            "3     0",
            "4      ",
            "       ",
            "      5",
            "9     6",
            "  8 7  ",

            "t",
            "SB",
            "   0   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "    2  ",
            "      3",

            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "u",
            "S",
            "       ",
            "       ",
            "0     7",
            "       ",
            "       ",
            "       ",
            "       ",
            "1     6",
            "  2 5  ",

            "v",
            "S",
            "       ",
            "       ",
            "0     4",
            "       ",
            " 1   3 ",
            "       ",
            "       ",
            "       ",
            "   2   ",

            "w",
            "S",
            "       ",
            "       ",
            "0     4",
            "   2   ",
            "       ",
            "       ",
            "       ",
            "       ",
            " 1   3 ",

            "x",
            "B",
            "       ",
            "       ",
            "0     3",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "2     1",

            "y",
            "SS",
            "       ",
            "      3",
            "       ",
            "       ",
            "       ",
            "       ",
            "     2 ",
            "    1  ",
            "0      ",

            "       ",
            "  0    ",
            "       ",
            "       ",
            "       ",
            "       ",
            "     1 ",
            "       ",
            "       ",

            "z",
            "S",
            "       ",
            "       ",
            "0    1 ",
            "      2",
            "       ",
            "       ",
            "       ",
            "3      ",
            " 4    5",
// CAPITAL A-Z

            "A",
            "SB",
            "   1   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     2",

            "       ",
            "       ",
            "       ",
            "       ",
            " 0   1 ",
            "       ",
            "       ",
            "       ",
            "       ",

            "B",
            "SS",
            "0   1  ",
            "     2 ",
            "       ",
            "     3 ",
            "9   4  ",
            "       ",
            "      5",
            "      6",
            "8    7 ",

            "0      ",
            "       ",
            "       ",
            "       ",
            "1   2  ",
            "       ",
            "       ",
            "       ",
            "       ",

            "C",
            "S",
            "  2 1  ",
            "3     0",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "4     7",
            "  5 6  ",

            "D",
            "L",
            "3  2   ",
            "     1 ",
            "       ",
            "      0",
            "       ",
            "      7",
            "       ",
            "     6 ",
            "4  5   ",

            "E",
            "SS",
            "1     0",
            "       ",
            "       ",
            "       ",
            "2    3 ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",
            "       ",
            "       ",
            "       ",
            "1     2",

            "F",
            "SB",
            "1     0",
            "       ",
            "       ",
            "       ",
            "2    3 ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",
            "       ",
            "       ",
            "       ",
            "1      ",

            "G",
            "S",
            "  2 1  ",
            "      0",
            "3      ",
            "       ",
            "   9  8",
            "       ",
            "4      ",
            "      7",
            "  5 6  ",

            "H",
            "B",
            "0     2",
            "       ",
            "       ",
            "       ",
            "4     5",
            "       ",
            "       ",
            "       ",
            "1     3",

            "I",
            "B",
            "0  2  1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "4  3  5",

            "J",
            "S",
            "      0",
            "       ",
            "       ",
            "       ",
            "       ",
            "      1",
            "       ",
            "     2 ",
            "4 3    ",

            "K",
            "BS",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "1      ",

            "      0",
            "       ",
            "       ",
            "       ",
            "1      ",
            "       ",
            "       ",
            "       ",
            "      2",

            "L",
            "S",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "1     2",

            "M",
            "SS",
            "  2    ",
            "1  3   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   4   ",
            "0      ",

            "    1  ",
            "   0  2",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "      3",

            "N",
            "S",
            "1     3",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     2",

            "O",
            "L",
            "   3   ",
            " 2   4 ",
            "       ",
            "1     5",
            "       ",
            "0     6",
            "       ",
            " 9   7 ",
            "   8   ",

            "P",
            "LB",
            "1   2  ",
            "      3",
            "      4",
            "0   5  ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "1      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",

            "Q",
            "LB",
            "   3   ",
            " 2   4 ",
            "       ",
            "1     5",
            "       ",
            "0     6",
            "       ",
            " 9   7 ",
            "   8   ",

            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "       ",
            "       ",
            "      0",

            "R",
            "LB",
            "2   3  ",
            "      4",
            "       ",
            "      5",
            "1   0  ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "1   3  ",
            "       ",
            "       ",
            "       ",
            "0     2",

            "S",
            "S",
            "   21  ",
            " 3    0",
            "       ",
            "4      ",
            "       ",
            "      5",
            "       ",
            "9    6 ",
            "  87   ",

            "T",
            "B",
            "0  2  1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   3   ",

            "U",
            "S",
            "0     7",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "1     6",
            "  2 5  ",

            "V",
            "S",
            "0     2",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",

            "W",
            "S",
            "0     4",
            "       ",
            "   2   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            " 1   3 ",

            "X",
            "B",
            "0     3",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "2     1",

            "Y",
            "SB",
            "0     2",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "       ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "   0   ",
            "       ",
            "       ",
            "       ",
            "   1   ",

            "Z",
            "S",
            "0     1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "2     3",

// various

            "'",
            "B",
            "       ",
            "   0   ",
            "   1   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            ",",
            "B",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "    1  ",
            "       ",
            "  0    ",

            ".",
            "B",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "   0   ",

            "!",
            "B",
            "   3   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   2   ",
            "       ",
            "   1   ",
            "   0   ",

            ":",
            "B",
            "       ",
            "   3   ",
            "   2   ",
            "       ",
            "       ",
            "       ",
            "   0   ",
            "   1   ",
            "       ",

            "/",
            "B",
            "      1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",

            "\\",
            "B",
            "0      ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "      1",

            "-",
            "B",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",
            "       ",

            "+",
            "B",
            "       ",
            "   2   ",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "   3   ",
            "       ",

            "=",
            "B",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",
            "2     3",
            "       ",
            "       ",

            "_",
            "B",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0     1",

            ";",
            "B",
            "       ",
            "   3   ",
            "   2   ",
            "       ",
            "       ",
            "       ",
            "   0   ",
            "       ",
            " 1     ",

            "|",
            "B",
            "   0   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",

            "<",
            "S",
            "       ",
            "      0",
            "       ",
            "       ",
            "1      ",
            "       ",
            "       ",
            "      2",
            "       ",

            ">",
            "S",
            "       ",
            "0      ",
            "       ",
            "       ",
            "      1",
            "       ",
            "       ",
            "2      ",
            "       ",

            "?",
            "SB",
            "  65   ",
            "7    4 ",
            "      3",
            "      2",
            "     1 ",
            "   0   ",
            "       ",
            "       ",
            "       ",

            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   1   ",
            "   0   ",

            "@",
            "SS",
            "  9 8  ",
            "       ",
            "      7",
            "   1 0 ",
            "  2    ",
            "  3   6",
            "   4 5 ",
            "       ",
            "       ",

            "  0    ",
            "       ",
            "1      ",
            "       ",
            "       ",
            "       ",
            "2      ",
            "       ",
            "  3   4",

            "[",
            "S",
            "   1  0",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   2  3",

            "]",
            "S",
            "0  1   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "3  2   ",

            "{",
            "S",
            "    1 0",
            "       ",
            "       ",
            "   2   ",
            "     3 ",
            "   4   ",
            "       ",
            "       ",
            "    5 6",

            "}",
            "S",
            "0 1    ",
            "       ",
            "       ",
            "   2   ",
            " 3     ",
            "   4   ",
            "       ",
            "       ",
            "6 5    ",

            "#",
            "B",
            "       ",
            " 3   1 ",
            "       ",
            "4     5",
            "       ",
            "6     7",
            "       ",
            " 2   0 ",
            "       ",

            "~",
            "S",
            "       ",
            "       ",
            "       ",
            " 12   5",
            "0   34 ",
            "       ",
            "       ",
            "       ",
            "       ",

            "\"",
            "B",
            " 0   2 ",
            " 1   3 ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "£",
            "SB",
            "  2 1  ",
            "3     0",
            "       ",
            " 4     ",
            "       ",
            "  5    ",
            "       ",
            " 6     ",
            "7     8",

            "       ",
            "       ",
            "       ",
            "       ",
            "0     1",
            "       ",
            "       ",
            "       ",
            "       ",

            "$",
            "SB",
            "       ",
            "  2 1  ",
            "3     0",
            "4      ",
            "       ",
            "      5",
            "9     6",
            "  8 7  ",
            "       ",

            "   0   ",
            "   1   ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "   2   ",
            "   3   ",

            "%",
            "LLB",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "    54 ",
            "   6  3",
            "   7  2",
            "    01 ",

            " 54    ",
            "6  3   ",
            "7  2   ",
            " 01    ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "      1",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "0      ",

            "^",
            "S",
            "   1   ",
            "       ",
            " 0   2 ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "&",
            "SB",
            "       ",
            "  7 6  ",
            " 8   5 ",
            "    4  ",
            " 9     ",
            "      0",
            "3      ",
            "     1 ",
            "   2   ",

            "       ",
            "       ",
            "       ",
            "       ",
            " 0     ",
            "       ",
            "       ",
            "       ",
            "      1",

            "*",
            "B",
            "  402  ",
            "  7 6  ",
            "  315  ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",
            "       ",

            "(",
            "S",
            "     10",
            "    2  ",
            "       ",
            "   3   ",
            "       ",
            "   4   ",
            "       ",
            "    5  ",
            "     67",

            ")",
            "S",
            "01     ",
            "  2    ",
            "       ",
            "   3   ",
            "       ",
            "   4   ",
            "       ",
            "  6    ",
            "87     ",
    };
    public static int[] cachedFont = new int[256];

    protected static void drawChar(char c) {
        // bit of a hypocrite here, rendering each char individually, but strings are at a higher layer.
        // hopefully the 1 array lookup and 1 call-list is fast enough?
        boolean isCompiling = false;
        if (c < cachedFont.length) {
            if (cachedFont[c] != 0) {
                GL11.glCallList(cachedFont[c]);
                return;
            } else {
                int lst = GL11.glGenLists(1);
                GL11.glNewList(lst, GL11.GL_COMPILE_AND_EXECUTE);
                cachedFont[c] = lst;
                isCompiling = true;
            }
        }
        int p = getCharLoc(c);
        if (p == -1) {
            if (isCompiling)
                GL11.glEndList();
            return;
        }
        char[] passes = fontDB[p++].toCharArray();
        String[] passData = new String[passes.length * 9];
        for (int i = 0; i < passData.length; i++)
            passData[i] = fontDB[p++];
        int passPos = 0;
        for (int i = 0; i < passes.length; i++) {
            char type = passes[i];
            int t = GL11.GL_LINE_STRIP;
            if (type == 'B')
                t = GL11.GL_LINES;
            double[] x = new double[10];
            double[] y = new double[10];
            boolean[] isUsed = new boolean[10];
            for (int j = 0; j < 9; j++) {
                String str = passData[passPos++];
                for (int n = 0; n < 10; n++)
                    if (str.contains(String.valueOf((char) ('0' + n)))) {
                        x[n] = str.indexOf(String.valueOf((char) ('0' + n)));
                        y[n] = j;
                        isUsed[n] = true;
                    }
            }
            GL11.glBegin(t);
            for (int n = 0; n < 10; n++)
                if (isUsed[n])
                    GL11.glVertex2d(x[n], y[n]);
            if (type == 'L')
                GL11.glVertex2d(x[0], y[0]);
            GL11.glEnd();
        }
        if (isCompiling)
            GL11.glEndList();
    }

    private static int[] cachedPositions = new int[256];

    public static int getCharLoc(char c) {
        boolean canCache = c < 256;
        if (canCache)
            if (cachedPositions[(int) c] != 0)
                return cachedPositions[(int) c];
        int p = 0;
        while (p < fontDB.length) {
            String activeChars = fontDB[p++];
            if (activeChars.contains(String.valueOf(c))) {
                if (canCache)
                    cachedPositions[(int) c] = p;
                return p;
            }
            String passes = fontDB[p++];
            p += passes.length() * 9;
        }
        if (canCache)
            cachedPositions[(int) c] = -1;
        return -1;
    }
}
